# Generated by Django 5.1.4 on 2024-12-14 03:45

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='mySlug',
            field=models.SlugField(blank=True, default=uuid.uuid4),
        ),
        migrations.RemoveField(
            model_name='recording',
            name='triggers',
        ),
        migrations.CreateModel(
            name='RecordingTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('icon', models.TextField(blank=True, default='', max_length=500)),
                ('mySlug', models.SlugField(blank=True, default=uuid.uuid4)),
                ('filterInclusively', models.BooleanField(default=True)),
                ('filterPriority', models.IntegerField(default=10)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recordings.recordingtrigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='triggers',
            field=mptt.fields.TreeManyToManyField(related_name='catalogitems', to='recordings.recordingtrigger'),
        ),
    ]
