# Generated by Django 5.1.4 on 2024-12-21 06:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_recording_myslug_remove_recording_triggers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_url', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_publish_date', models.DateTimeField(blank=True, null=True)),
                ('mySlug', models.SlugField(blank=True, default=uuid.uuid4)),
            ],
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='published_date',
            new_name='last_publish_date',
        ),
        migrations.AlterField(
            model_name='recording',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.recordingsource'),
        ),
    ]
