# Generated by Django 5.1.4 on 2024-12-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_recordingsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsource',
            name='broadcast_url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
