# Generated by Django 5.1.4 on 2024-12-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_recordingsource_broadcast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsource',
            name='broadcast_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='recordingsource',
            name='source_url',
            field=models.URLField(),
        ),
    ]
