# Generated by Django 5.1.4 on 2024-12-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0006_recordingsource_rebroadcast_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordingsource',
            name='broadcast_url',
        ),
    ]
