# Generated by Django 5.1.4 on 2024-12-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0007_remove_recordingsource_broadcast_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsource',
            name='hls_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
