# Generated by Django 5.1.4 on 2025-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0008_recordingsource_hls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsource',
            name='has_recordings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordingsource',
            name='recording_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordingsource',
            name='stream_type',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Audio'), (1, 'Video')], default=-1),
        ),
    ]
