# Generated by Django 5.1.4 on 2025-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0009_recordingsource_has_recordings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsource',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
