# Generated by Django 5.1.4 on 2025-03-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0010_recordingsource_recording_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingsource',
            name='recording_worker_id',
            field=models.IntegerField(default=-1),
        ),
    ]
